# Generated by Django 3.2.12 on 2022-04-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_auto_20220322_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='star',
            field=models.SmallIntegerField(choices=[(0, 'Нет оценки'), (1, 'Ненависть'), (2, 'Неприязнь'), (3, 'Нейтрально'), (4, 'Обожание'), (5, 'Любовь')], default=0, verbose_name='Оценка'),
        ),
    ]
