# Generated by Django 3.2.12 on 2022-04-11 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_category_name'),
        ('rating', '0005_alter_rating_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_stars', to='catalog.item', verbose_name='Товар'),
        ),
    ]
