# Generated by Django 3.2.12 on 2022-03-20 12:47

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Максимальная длинна 150', max_length=150, verbose_name='Имя')),
                ('text', models.TextField(help_text='Минимум 2 слова', validators=[catalog.validators.validate_brilliant, catalog.validators.ValidateWordsCount(2)], verbose_name='Описание')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликованно')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
