# Generated by Django 3.2.12 on 2022-03-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликованно')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'abstract': False,
            },
        ),
    ]
