# Generated by Django 3.2.12 on 2022-03-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(related_name='items', to='catalog.Tag', verbose_name='Теги'),
        ),
    ]
