# Generated by Django 3.2.12 on 2022-03-21 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_auto_20220321_1031'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0004_auto_20220321_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ratings',
            field=models.ManyToManyField(related_name='items', through='rating.Rating', to=settings.AUTH_USER_MODEL, verbose_name='Оценки'),
        ),
    ]
