# Generated by Django 3.2.12 on 2022-04-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Имя'),
        ),
    ]
