# Generated by Django 3.2.12 on 2022-04-27 15:32

import catalog.validators
from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20220427_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=tinymce.models.HTMLField(help_text='Минимум 2 слова', validators=[catalog.validators.validate_brilliant, catalog.validators.ValidateWordsCount(2)], verbose_name='Описание'),
        ),
    ]
